import { FaHome } from "react-icons/fa"
import { FaBagShopping } from "react-icons/fa6";
import { useNavigate } from "react-router-dom"

interface OrderItemType {
    name: string,
    price: number,
    quantity: number,
    imageUrl: string,
    product: string,
    // _id: string,
}
interface paymentInfoType {
    id: string,
    status: string,
}
interface OrderDataType {
    id: string,
    address: string,
    city: string,
    state: string,
    country: string,
    pinCode: number,
    phoneNo: number,
    orderedItems: Array<OrderItemType>,
    user: string,
    paymentInfo: paymentInfoType,
    itemsPrice: number,
    taxPrice: number,
    shippingPrice: number,
    totalPrice: number,
    orderStatus: string,
}
const MyOrder = () => {
    const Order: OrderDataType[] = [
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
        {
            id: "orderID",
            address
                :
                "Home",
            city
                :
                "Jodhpur",
            country
                :
                "India",
            itemsPrice
                :
                2676,
            orderStatus
                :
                "Processing",
            orderedItems
                : [
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                    {
                        imageUrl
                            :
                            "https://m.media-amazon.com/images/I/91UdWh7kiwL._SX569_.jpg",
                        name
                            :
                            "tshirt",
                        price
                            :
                            669,
                        product
                            :
                            "6619ea48c112fa07f48b1ae8",
                        quantity
                            :
                            1,
                    },
                ],
            paymentInfo: {
                id: "",
                status: "notpaid",
            },
            phoneNo: 1000002222,
            pinCode: 342001,
            shippingPrice: 70,
            state
                :
                "Rajasthan",
            taxPrice
                :
                15,
            totalPrice
                :
                2761,
            user: "userid"
        },
    ]
    const navigate = useNavigate();
    return (
        <div className="MyOrderContainer">
            <div><FaHome style={{ cursor: "pointer", margin: "1rem" }} onClick={() => navigate("/")} size={25} color="gray" /></div>
            <main>
                <h2><FaBagShopping size={30} color="gray" /></h2>
                <table>

                    <tbody>
                        {Order.length > 0 ?
                            <>
                                <tr>
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Amount
                                    </th>
                                    <th>
                                        Status
                                    </th>
                                </tr>
                                {Order.map((item) => (
                                    <tr>
                                        <td>{item.id}</td>
                                        {/* <td>{item.orderedItems.length}</td> */}
                                        <td>Rs.{item.totalPrice}/-</td>
                                        <td>{item.orderStatus}</td>
                                    </tr>
                                ))
                                }
                            </> : <p>No Order Yet</p>
                        }
                    </tbody>
                </table>
            </main>
        </div>
    )
}

export default MyOrder